### ISSUE TITLE
Questions & suggestions

### ISSUE THREAD

**Issue by cheapsteak** [codevcode/compose-with-scope#1]
What's the difference between `consumeProps` (typo in the readme btw, says consumProps) and `injectProps`?

Would recommend renaming `passProps/passHandlers` to either `exposeProps` or `exportProps` since "pass" is ambiguous as to whether it's passed "in" or passed "out"

Going to self-close since this is not an issue

**Comment by Isaddo** [comment]
`consumeProps` pass props in the scope and will consume props when leaving the scope.
`injectProps` also pass props in but still pass these props to the base component.

I used to use `consumeProps` to declare the props to be processed by enhancer and 
use `injectProps` to inject some props I treate them like global variables(ex. `eventEmitter)

```js
composeWithScope(
  consumeProps({ location: propTypes.object, match: propTypes.object }),
  injectProps({ eventEmitter: propTypes.object }),
  ...enhancers,
)
```

**Comment by Isaddo** [comment]
`exposeProps` and `exposeHandlers` sounds good!!

"pass" also makes me a little confused, but I could not think of a better word at that time.
I have considered "export", but IMO it has been used for modules and uncertain whether the scope can be considered as module.

Thanks the suggestion, I will rename them later! Naming always a hard work for me.

Amending the doc or my English is welcome btw.
